### ISSUE TITLE
"gsteamclean.exe returned -1" error when starting gsteamclean.exe.

### ISSUE THREAD

**Issue by Fooughhy** [evitalis/steamclean#10]
So I just downloaded the new release (v.0.5.2) and when I start gsteamclean.exe I get this error as a popup:
> "gsteamclean.exe returned -1"

If I start it as admin, I still get the error. After I click "Ok", the program still doesn't open.

I get no log when this happens, but the log I get for the regular "steamclean.exe" looks like this:

> 2016-01-05 13:03:18 WARNING: Unable to read script information from file steamclean.py
> 2016-01-05 13:03:18 INFO: 64bit operating system detected> 
> 2016-01-05 13:03:18 INFO: Registry data at HKEY_LOCAL_MACHINE\SOFTWARE\Wow6432Node\Valve\Steam used to determine installation path
> 2016-01-05 13:03:18 INFO: Steam installation path found at C:\Program Files (x86)\Steam
> 2016-01-05 13:03:18 INFO: Game installations located at C:\Program Files (x86)\Steam\SteamApps\common
> 2016-01-05 13:03:18 INFO: Checking C:\Program Files (x86)\Steam\SteamApps\common

**Comment by evitalis** [comment]
Another result from the CLI:

    Checking E:\Steam\SteamApps\common
    Traceback (most recent call last):
      File "<string>", line 368, in <module>
      File "<string>", line 225, in find_redist
    IndexError: list index out of range
    steamclean returned -1

**Comment by evitalis** [comment]
Please try version 0.5.3 and let me know if this is resolved. I tried to catch more errors that may result in this.

**Comment by Fooughhy** [comment]
The program starts now, atleast, so this "bug" has been fixed.

I'm still unable to clean anything as no files are displayed when I scan.
Should I post the log here, or create a new issue?

**Comment by evitalis** [comment]
Please attach the log if able. Are you also supplying extra directories to have checked, or only the default?

**Comment by Fooughhy** [comment]
I am run it with and without extra steam directories, with the same result.
[steamclean_20160107-1322.txt](https://github.com/evitalis/steamclean/files/81117/steamclean_20160107-1322.txt)

**Comment by evitalis** [comment]
If possible can you try to run the script found in the dev branch directly? Either should work as the code is shared. I added some logging which may catch or ignore the offending file.

**Comment by evitalis** [comment]
Commit  cf1a0ba should catch this will extra logging. 
Error -1 is generic, to get full error please run the source script from a terminal window to help narrow the cause down.
