### ISSUE TITLE
Feature request: Operation timing

### ISSUE THREAD

**Issue by evitalis** [evitalis/steamclean#17]
Include in the log the amount of time taken by each operation. Include scan time and cleaning time.

**Comment by evitalis** [comment]
This can be found by reading the log and comparing first and last timestamp. Setting to lower priority for the time being.

**Comment by sam97** [comment]
Would it be better to calculate time taken using the difference in start and stop times of operations?

**Comment by evitalis** [comment]
@sam97 That would be good. Some of the existing functions might need cleaned up though otherwise the timing would happen on multiple operations at once.

**Comment by sam97** [comment]
I'll try testing that. (No promises yet)
I was thinking three times, "time to scan", "time to clean", and "time of this session". Is that alright, or is there more?

**Comment by evitalis** [comment]
Those sound fine to me. I have not had time to revisit lately but am going to try and work on some code cleanup this week. Feel free to do pull requests against the dev branch however.

**Comment by evitalis** [comment]
Merge request accepted.
