### ISSUE TITLE
File not found if default steam does not exist

### ISSUE THREAD

**Issue by caboose0013** [evitalis/steamclean#6]
I don't have any games install on the c drive eq. C:\Program Files (x86)\Steam\SteamApps\common does not exist and the script fails:
Checking C:\Program Files (x86)\Steam\SteamApps\common
Traceback (most recent call last):
  File "<string>", line 368, in <module>
  File "<string>", line 139, in find_redist
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'C:\\Program Files(x86)\\Steam\\SteamApps\\common'
steamclean returned -1

**Comment by evitalis** [comment]
Can you check the file explorer for the path to ensure it is valid please? On my system I also did not install anything to C:\ as that is my SSD which I do not wish to clutter up.
```
C:\Program Files (x86)\Steam\steamapps\common>dir
 Volume in drive C has no label.
 Volume Serial Number is XXXX-XXXX

 Directory of C:\Program Files (x86)\Steam\steamapps\common

08/22/2015  12:09    <DIR>          .
08/22/2015  12:09    <DIR>          ..
               0 File(s)              0 bytes
               2 Dir(s)  98,086,707,200 bytes free
```

**Comment by caboose0013** [comment]
I manually created the common directory in steamspps on c:\ and it worked
just fine

**Comment by evitalis** [comment]
I do not expect that it should have errored out though. I am going to set it as a bug for the moment and will review the code again. I might just be missing a check somewhere.

**Comment by evitalis** [comment]
I added some extra tests for the missing or invalid directory in commit 14867e4117898. This should be resolved but will leave open until the next build is posted and tested.

**Comment by evitalis** [comment]
v0.6.0 allows for less restrictions on directory names and additional logging was added which should resolve this. Merge commit  cf1a0ba .
