### ISSUE TITLE
Directories are changed even if you click "Cancel" in the popup.

### ISSUE THREAD

**Issue by Fooughhy** [evitalis/steamclean#7]
I am still unable to use the application since I have the same issue as this guy: 
https://www.reddit.com/r/Steam/comments/3z360o/steamclean_v051_released/cyj29kk

But with the functionality I can access, there's still some bugs I can report.

When you click the "Add dir" or "..." button in the window you get a popup. Here you can click "Choose folder" (translated from Swedish) or "Cancel". But if you click "Cancel", the folder is still chosen, so if you clicked "Add dir" and then "Cancel" the folder is still added to the list of directories.

**Comment by evitalis** [comment]
Corrected by commit 0668670e994d72c87bb81cf2b050e2b8a876b461
